language: java

install: true

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle

before_script:
    - ./gradlew --version

script:
    - TERM=dumb ./gradlew build jacocoTestReport jacocoRootReport

jdk:
    - oraclejdk8

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

after_success:
    ./gradlew coveralls
