
[[_Usage]]
= Usage

The following sections describe how you may use this plugin in a project.

== Configuration

This plugin relies on the {link_griffon_datasource_plugin}. Please follow the instructions to configure this plugin first.

You must create a configuration file named `Mybatis` that holds the settings for creating instances of `{link_sql_session_factory}`.
This file follows the same standard configuration mechanism as the application's `Config` file, which means you can define the
configuration using

 * a properties file
 * a Java file
 * a Groovy script

The following example shows the default settings needed to connect the default database taking into account that each
environment may connect to a different database.

[source,groovy,options="nowrap"]
.src/main/resources/Mybatis.groovy
----
include::{path_griffon_mybatis_core}/src/test/resources/Mybatis.groovy[lines=18..39]
----

You may configure multiple named SqlSessionFactories (the default factory is aptly named `default`) as the following snippet
shows

[source,groovy,options="nowrap"]
.src/main/resources/Mybatis.groovy
----
include::{path_griffon_mybatis_core}/src/test/resources/Mybatis.groovy[lines=41..48]
----

The following properties are optional

[cols="4*",options="header"]
|===
| Property           | Type    | Default | Description
| connect_on_startup | boolean | false   | Establishes a connection to the datasource at the beginning of the `Startup` phase.
| jmx                | boolean | true    | Expose sessions using JMX.
| pooled             | boolean | true    | Whether to use Hikari as connection pool or not.
|===

The plugin's <<_modules, module>> registers a `{api_mybatis_handler}` helper class that defines the base contract
for accessing a datasource and issue SQL queries to it. This class has the following methods

[source,java,options="nowrap"]
.griffon.plugins.mybatis.MybatisHandler.java
----
include::{path_griffon_mybatis_core}/src/main/java//griffon/plugins/mybatis/MybatisHandler.java[tags=methods,indent=0]
----

These method are aware of multiple datasources. If no sessionFactoryName is specified when calling them then the default
datasource will be selected. You can inject an instance of this class anywhere it's needed using `@Inject`. There is one
callback you may use with this method: `{api_mybatis_callback}`.

This callback is defined using a functional interface approach, which means you can apply lambda expressions if running
with JDK8+ or closures if running Groovy.

[source,java,options="nowrap"]
.griffon.plugins.mybatis.MybatisCallback.java
----
include::{path_griffon_mybatis_core}/src/main/java/griffon/plugins/mybatis/MybatisCallback.java[lines=28..-1]
----

=== Mappers

MyBatis requires a mapper class for each type you'd like to map to a table. The plugin can automatically discover mappers
that should be added to a `{link_sql_session_factory}` as long as they are annotated with `@TypeProviderFor`. For example

[source,groovy,options="nowrap"]
.src/main/groovy/griffon/plugins/mybatis/mappers/PersonMapper.groovy
----
include::{path_griffon_mybatis_core}/src/test/groovy/griffon/plugins/mybatis/mappers/PersonMapper.groovy[lines=18..-1]
----

Don't forget mappers require a matching XML file that contains query definitions, such as

[source,xml,options="nowrap"]
[subs="verbatim,attributes"]
.src/main/resources/griffon/plugins/mybatis/mappers/PersonMapper.xml
----
include::{path_griffon_mybatis_core}/src/test/resources/griffon/plugins/mybatis/mappers/PersonMapper.xml[lines=23..-1]
----

=== Bootstrap

You may execute arbitrary database calls during connection and disconnection from a `{link_sql_session_factory}`. Simply
create a class that implements the `{api_mybatis_bootstrap}` interface and register it within a module, for example

[source,java,options="nowrap"]
.src/main/java/com/acme/SampleMybatisBootstrap.java
----
package com.acme;

import griffon.plugins.mybatis.MybatisBootstrap;
import org.apache.ibatis.session.SqlSession;

import javax.annotation.Nonnull;
import javax.inject.Named;

@Named("sample")
public class SampleMybatisBootstrap implements MybatisBootstrap {
    @Override
    public void init(@Nonnull String sessionFactoryName, @Nonnull SqlSession session) {
        // operations after first connection to datasource
    }

    @Override
    public void destroy(@Nonnull String sessionFactoryName, @Nonnull SqlSession session) {
        // operations before disconnecting from the datasource
    }
}
----

[source,java,options="nowrap"]
.src/main/java/com/acme/ApplicationModule.java
----
package com.acme;

import griffon.plugins.mybatis.MybatisBootstrap;
import griffon.core.injection.Module;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.ServiceProviderFor;

@ServiceProviderFor(Module.class)
public class ApplicationModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(MybatisBootstrap.class)
            .to(SampleMybatisBootstrap.class)
            .asSingleton();
    }
}
----

== Example

The following is a trivial usage of the `{api_mybatis_handler}` inside a Java service

[source,java,options="nowrap"]
.com.acme.SampleService.java
----
package com.acme;

import griffon.core.artifact.GriffonService;
import org.codehaus.griffon.runtime.core.artifact.AbstractGriffonService;

import griffon.plugins.mybatis.MybatisHandler;
import griffon.plugins.mybatis.MybatisCallback;
import org.apache.ibatis.session.SqlSession;
import org.kordamp.jipsy.ServiceProviderFor;

import com.acme.mappers.PersonMapper;

import javax.annotation.Nonnull;
import javax.inject.Inject;

@ServiceProviderFor(GriffonService.class)
public class SampleService extends AbstractGriffonService {
    @Inject
    private MybatisHandler mybatisHandler;

    public String getPersonName(final int id) {
         return mybatisHandler.withSqlSession(new MybatisCallback<String>() {
             public String handle(@Nonnull String sessionFactoryName, @Nonnull SqlSession session) {
                 PersonMapper mapper = session.getMapper(PersonMapper.class);
                 Person person = mapper.findPersonById(id);
                 return person != null ? person.getName() : null;
         });
    }
}
----

Here's the Groovy version of it

[source,groovy,options="nowrap"]
.com.acme.SampleService.groovy
----
package com.acme

import griffon.core.artifact.GriffonService

import griffon.plugins.mybatis.MybatisHandler
import org.apache.ibatis.session.SqlSession
import org.kordamp.jipsy.ServiceProviderFor

import com.acme.mappers.PersonMapper

import javax.inject.Inject

@ServiceProviderFor(GriffonService)
class SampleService {
    @Inject
    private MybatisHandler mybatisHandler

    String getPersonName(int id) {
         mybatisHandler.withSqlSession { String sessionFactoryName, SqlSession session ->
             session.getMapper(PersonMapper)?.findPersonById(id)?.name
         }
    }
}
----

== Events

The following events will be triggered by `{api_mybatis_handler}`

MybatisConnectStartEvent(String sessionFactoryName, Map<String, Object> config):: Triggered before connecting to the datasource.
MybatisConnectEndEvent(String sessionFactoryName, Map<String, Object> config, SqlSessionFactory factory):: Triggered after connecting to the datasource.
MybatisDisconnectStartEvent(String sessionFactoryName, Map<String, Object> config, SqlSessionFactory factory):: Triggered before disconnecting from the datasource.
MybatisDisconnectEndEvent(String sessionFactoryName, Map<String, Object> config):: Triggered after disconnecting from the datasource.

NOTE: DataSource events may be triggered during connection and disconnection from a `{link_sql_session_factory}`.

== AST Transformation

You can apply the `{api_mybatis_aware}` AST transformation on any class. This injects the behavior of `{api_mybatis_handler}`
into said class. The previous Groovy service example can be rewritten as follows

[source,groovy,options="nowrap"]
.com.acme.SampleService.groovy
----
package com.acme

import griffon.core.artifact.GriffonService
import griffon.transform.MybatisAware

import org.apache.ibatis.session.SqlSession
import org.kordamp.jipsy.ServiceProviderFor

import com.acme.mappers.PersonMapper

@MybatisAware
@ServiceProviderFor(GriffonService)
class SampleService {
    String getPersonName(int id) {
         withSqlSession { String sessionFactoryName, SqlSession session ->
             session.getMapper(PersonMapper)?.findPersonById(id)?.name
         }
    }
}
----

== DSL Descriptors

This plugin provides DSL descriptors for Intellij IDEA and Eclipse (provided you have the Groovy Eclipse plugin installed).
These descriptors are found inside the `griffon-mybatis-groovy-compile-{project-version}.jar`, with locations

 * dsdl/griffon_mybatis.dsld
 * gdsl/griffon_mybatis.gdsl
